import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ productos }) {
  console.log(productos.data);
  return (
    <div>
      <Head>
        <title>Strapi | Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.titulo}>
        Hola <i className="bi bi-apple"></i>!
      </h1>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:1337/api/productos?populate=*");
  const productos = await res.json();

  return { props: { productos } };
}
